### ISSUE TITLE
Error in PlasmoExamples

### ISSUE THREAD

**Issue by ChengweiLou** [zavalab/JuliaBox#1]
Sorry to bother you again. @jalving

When I finished installing the packages, I cannot wait to try to test all cases you mention in your paper.

I found the error as follow:
For the DC OPF:

It seems ModelNode not defined.

Error evaluating partition_and_solve.jl

LoadError: LoadError: UndefVarError: ModelNode not defined
in expression starting at /home/chengwei/JuliaBox/PlasmoExamples/case_studies/dcpowergrid/powergrid.jl:21
in expression starting at /home/chengwei/JuliaBox/PlasmoExamples/case_studies/dcpowergrid/partition_and_solve.jl:4
(::getfield(Main, Symbol("##27#28")))(::OptiNode) at none:0
iterate at generator.jl:47 [inlined]
_all(::getfield(Base, Symbol("##220#222")), ::Base.Generator{Array{OptiNode,1},getfield(Main, Symbol("##27#28"))}, ::Colon) at reduce.jl:660
all at reduce.jl:656 [inlined]
Dict(::Base.Generator{Array{OptiNode,1},getfield(Main, Symbol("##27#28"))}) at dict.jl:131
top-level scope at none:0
include at boot.jl:317 [inlined]
include_relative(::Module, ::String) at loading.jl:1044
include(::Module, ::String) at sysimg.jl:29
include(::String) at client.jl:392
top-level scope at none:0

Another is a small issue about gas example:

I can see file 13_pipelines.jld2 in the folder, but cannot open it.

I think I can try to find the way.

Error evaluating partition_and_solve.jl

LoadError: LoadError: LoadError: SystemError: opening file 13_pipelines.jld2: No such file or directory
in expression starting at /home/chengwei/JuliaBox/PlasmoExamples/case_studies/gasnetwork/load_data.jl:3
in expression starting at /home/chengwei/JuliaBox/PlasmoExamples/case_studies/gasnetwork/gasnetwork.jl:11
in expression starting at /home/chengwei/JuliaBox/PlasmoExamples/case_studies/gasnetwork/partition_and_solve.jl:1
#systemerror#39(::Nothing, ::Function, ::String, ::Bool) at error.jl:106
systemerror at error.jl:106 [inlined]
#open#295(::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Function, ::String) at iostream.jl:283
#open at JLD2.jl:0 [inlined]
openfile at JLD2.jl:186 [inlined]
openfile(::Type, ::String, ::Bool, ::Bool, ::Bool, ::Type) at JLD2.jl:197
#jldopen#9(::Type{IOStream}, ::Bool, ::Bool, ::Function, ::String, ::Bool, ::Bool, ::Bool, ::Type{JLD2.MmapIO}) at JLD2.jl:249
jldopen(::String, ::Bool, ::Bool, ::Bool, ::Type{JLD2.MmapIO}) at JLD2.jl:213
#jldopen#10(::Type, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::String, ::String) at JLD2.jl:305
jldopen(::String, ::String) at JLD2.jl:300
top-level scope at none:0
include at boot.jl:317 [inlined]
include_relative(::Module, ::String) at loading.jl:1044
include(::Module, ::String) at sysimg.jl:29
include(::String) at client.jl:392
top-level scope at none:0
include at boot.jl:317 [inlined]
include_relative(::Module, ::String) at loading.jl:1044
include(::Module, ::String) at sysimg.jl:29
include(::String) at client.jl:392
top-level scope at none:0

**Comment by jalving** [comment]
Hey @ChengweiLou .  Take a look at: https://github.com/jalving/PlasmoExamples for the updated examples.

It should at least work with Plasmo v0.3.0.  Feel free to send me an email if you still run into issues.

**Comment by ChengweiLou** [comment]
> Hey @ChengweiLou . Take a look at: https://github.com/jalving/PlasmoExamples for the updated examples.
> 
> It should at least work with Plasmo v0.3.0. Feel free to send me an email if you still run into issues.

Thank you. That is really helpful.

**Comment by ChengweiLou** [comment]
All solved.
